# Generated by Django 4.2.2 on 2023-06-10 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=16)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('buyer_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('harvest_date', models.DateField()),
                ('bag_type', models.CharField(max_length=10)),
                ('total_stock', models.IntegerField()),
                ('minimum_order', models.IntegerField()),
                ('price_per_kg', models.FloatField()),
                ('publish_date', models.DateField()),
                ('pickup_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RefundOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=16)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('seller_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('establishment_year', models.DateField()),
                ('address_proof', models.ImageField(upload_to='seller/address_proof')),
                ('bank_account_no', models.CharField(max_length=100)),
                ('bank_ifsc_code', models.CharField(max_length=100)),
                ('highest_qualification', models.CharField(max_length=100, null=True)),
                ('document_personal', models.ImageField(upload_to='seller/document_personal')),
                ('document_business_license', models.ImageField(upload_to='seller/document_business_license')),
                ('document_passbook', models.ImageField(upload_to='seller/document_passbook')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=16)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('transport_manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('poc_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.TextField()),
                ('hub_address', models.TextField()),
                ('gstin', models.CharField(max_length=100)),
                ('cin', models.CharField(max_length=100)),
                ('company_vehicles', models.IntegerField()),
                ('company_drivers', models.IntegerField()),
                ('company_labors', models.IntegerField()),
                ('license', models.ImageField(upload_to='transporter/license')),
                ('bank_account_no', models.CharField(max_length=100)),
                ('bank_ifsc_code', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.buyer')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.item')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.seller')),
                ('transport_manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.transporter')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.seller'),
        ),
    ]
