# Generated by Django 4.2.2 on 2023-06-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0002_alter_buyer_email_alter_seller_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Initiated', 'Initiated'), ('Completed', 'Completed'), ('Waiting for Seller', 'Waiting for Seller')], default='Initiated', max_length=100),
        ),
    ]
