# Generated by Django 4.2.2 on 2023-06-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0003_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
