# Generated by Django 4.2.2 on 2023-06-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0004_buyer_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default=0, upload_to='items/item_proof'),
            preserve_default=False,
        ),
    ]
