# Generated by Django 4.2.2 on 2023-06-14 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0005_item_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSelection',
            fields=[
                ('item_selection_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.item')),
            ],
        ),
    ]
