# Generated by Django 4.2.2 on 2023-06-14 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0006_itemselection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemselection',
            old_name='item_id',
            new_name='item',
        ),
    ]
